### ISSUE TITLE
Deviation from CBO baseline issue

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#860] opened 2016-08-12 14:10 UTC
As discussed in the web application [#300](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/300#issuecomment-239453057), a user added 50% to the baseline CBO growth rate and generated very odd results. A few other modest options do not work either. 

So it seems that there might be some bug in our growth capabilities. This issue will be further investigated.

**Comment by MattHJensen** [comment] 2016-08-12 19:11
- [ ] Once things get figured out over here, let's open an issue on webapp-public to rethink the user interface of the growth parameters and reinstate them.

**Comment by GoFroggyRun** [comment] 2016-08-17 03:41
I tried using a [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Growth.ipynb) to replicate the issue some users are experiencing on TB, which I wasn't able to do so. 

Based on the reform listed [here](http://www.ospc.org/taxbrain/edit/4900/?start_year=2016), I assumed two different growth rate under this reform, one of 0.05 and the other of 0.5, and compared them with our baseline. The results using a notebook look completely different from the webapp-cached [result](http://www.ospc.org/taxbrain/4900/). 

I'm not sure whether I'm missing something or not. From my perspective, however, there might be some issue in TB, rather than TC.

@MattHJensen

**Comment by talumbau** [comment] 2016-08-17 16:03
We are hiding Growth Parameters on TaxBrain right now due to this bug, but I checked the database and it is true that Taxbrain run 4900 that @GoFroggyRun links above does have a _factor_adjustment value of 0.5, so if that is wildly different from the notebook above, then there is likely a bug on TaxBrain side.

**Comment by GoFroggyRun** [comment] 2016-08-18 01:36
I have updated the notebook, which adds an identical reform as shown [here] (http://www.ospc.org/taxbrain/edit/4900/?start_year=2016). 

Since the growth rate option is being removed from TB temporarily, I was trying to see whether the remaining reform options would yield identical result in TB and TC. 

Based on the result [here](http://www.ospc.org/taxbrain/5148/) and the updated notebook [here](https://github.com/GoFroggyRun/Notebook/blob/master/Growth.ipynb), it's very likely that there's something wrong with the growth rate on TB's side.

**Comment by talumbau** [comment] 2016-08-18 20:22
@GoFroggyRun , I am continuing to track this down, but even if I ignore the growth adjustment parameters, I'm not getting results on TaxBrain or local runs of Tax-Calculator that align with the results that you show in the notebook. I'm wondering if you are either running an earlier or later version of Tax-Calculator than what I'm running. To track this issue, lets' run the latest release of Tax-Calculator. You can do this by uninstalling whatever version you have and running the following command:

```
conda install -c ospc taxcalc
```

Can you do this and then re-run your notebook with the following additional cell:

```
import taxcalc
taxcalc._version.get_versions()
```

if everything is good, then you will have the following output:
```
{'full': '4fb4abaca1388537137912419496ea8366c513a1', 'version': '0.6.6'}
```

When you get this output, please re-run the rest of the notebook and upload the results again. I can confirm that TaxBrain 4900 is definitely different from running the reform w/o any growth adjustment parameters, so we know that it is not ignoring those parameters. It may be incorporating them incorrectly though.

**Comment by GoFroggyRun** [comment] 2016-08-19 18:17
@talumbau Thanks for your comments on the notebook TJ! 

I have switched to the latest release of Tax-calculator, and included an additional cell which shows the version info. 
The first diagnostic table and the very last diagnostic table in my updated [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Growth.ipynb) shall align with the difference on this [page](http://www.ospc.org/taxbrain/5148/) .

cc @MattHJensen

**Comment by talumbau** [comment] 2016-08-19 22:40
Ok, thanks! I think we are now in a place where I can begin to understand if anything is wrong with the Growth assumptions section. As a baseline for this discussion, we know that if you just run the reform by itself (with no growth parameters), you will get nearly identical results (identical results are not expected due to the disclosure avoidance mechanism). So, to be specific, you can see that this TaxBrain job:

http://www.ospc.org/taxbrain/5178/

has essentially the same results as the diagnostic table for `calcreform3` (which has no growth parameters).

Continuing to look into this...

**Comment by talumbau** [comment] 2016-08-19 22:51
@GoFroggyRun I have investigated further and I don't see significant differences between [TaxBrain #4900](http://www.ospc.org/taxbrain/4900/) and `calcreform2` in the latest version of your notebook (which I can duplicate when I run your notebook locally). I didn't exhaustively compare every value, but when I look at AGI, Combined tax liability, Standard Deduction, and a few others for the years 2016 and 2020, I see substantially similar values in both tables (selecting "Diagnostic" and "Reform" in the table builder on TaxBrain). In some cases, the values are the same (at least out to the precision we print them to). Can you indicate which values you are concerned about?

**Comment by GoFroggyRun** [comment] 2016-08-19 23:20
@talumbau said:
>
but when I look at AGI, Combined tax liability, Standard Deduction, and a few others for the years 2016 and 2020, I see substantially similar values in both tables

Yes, right. When comparing the third table (`calcreform2` with 0.5 growth rate) with [TaxBrain #4900](http://www.ospc.org/taxbrain/4900/) alone, I do not see any significant difference as well. 

When I am, however, looking at the `TOTAL LIABILITIES CHANGE BY CALENDAR YEAR` on the web cache page, numbers in this table do not seem right. For each year, shouldn't these numbers be the difference between corresponding entires in `calcbase`'s table and in `calcreform2`'s table? 

In year 2016 say, the web page indicates $92.8 (b) in the Combined Payroll and Individual Income Tax Liability Change entry. In the notebook, combined liability for baseline is $2,503.7 (b) and combined liability for `calcreform2` is $4,221.8 (b). Subtracting the two numbers in the notebook does not yield consistent number as shown on the web page, while I was expecting some close result. Hope this clarifies my concern.

**Comment by talumbau** [comment] 2016-08-19 23:32
Ah, yes this came up in the original implementation. I don't have the issue number handy, but when  growth and behavioral assumptions were added to TaxBrain, I recall asking @MattHJensen and @Amy-Xu what the definition of "baseline" is in this case: is it "no reform and *with* the assumptions" or "no reform and no growth/behavior assumptions." The answer that I recall getting is that "baseline" is defined as "no reform *with* the growth and/or behavior assumptions." Therefore, you would have to run a baseline with no reform but the same growth parameters in your notebook to check the calculation.

**Comment by MattHJensen** [comment] 2016-08-20 00:31
> The answer that I recall getting is that "baseline" is defined as "no reform with the growth and/or behavior assumptions." 

For growth this is correct. The purpose of these growth parameters is allow for non-standard baselines. This allows us to answer questions like, "what would the revenue loss of this reform be if baseline growth were higher than CBO expects?" It would make sense to use this parameter in a few scenarios 1) you think that CBO is just wrong. 2) you have some other reform that you are proposing-- say a regulatory overhaul -- that isn't modeled by TaxBrain and isn't in CBO's baseline expectations, but would produce growth. 3) you think CBO does have the central estimate right, but you are risk averse and want to stress test your reform proposal.

**Comment by talumbau** [comment] 2016-08-20 01:09
OK, if that interpretation is correct, then I think we still need more detail on how [TaxBrain #4900](http://www.ospc.org/taxbrain/4900) differs from the notebook, or maybe more description in this issue:

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/300

on the "odd results"

**Comment by GoFroggyRun** [comment] 2016-08-20 01:25
Thanks @MattHJensen and @talumbau  for your explanations. I added the baseline that has ''no reform and with the assumptions'' in the [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Growth.ipynb). It turns out that there's no essential difference between results in TC and results in TB. 

I'll further investigate the odd results we are having.

**Comment by GoFroggyRun** [comment] 2016-08-24 22:42
After investigating the odd results, I don't think there's any bug in the tax logic. I have also updated the [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Growth.ipynb) that yields this conclusion.  

Let me present them in the following table (of combined lability):

![image](https://cloud.githubusercontent.com/assets/13324931/17950109/1d85f912-6a27-11e6-8254-2f2220fe6ad4.png)

![image](https://cloud.githubusercontent.com/assets/13324931/17950117/23d057cc-6a27-11e6-867e-7c8df4951002.png)

What I have done is simply separating the original reforms into two non-overlapping components: 
one that removes all surtax benefits (i.e. `_ID_BenefitSurtax_crt': [0.0]`) and the other one includes all the remaining reforms.

From the Diff row of two tables, I was able to explain what happened on this [cached page](http://www.ospc.org/taxbrain/4900/): 
**While two diffs are both expanding respectively in terms of absolute value, the positive diff starts with a higher initial value but a more modest expanding rate, and the negative one has a lower initial value but a more aggressive expanding rate.** 

 And that's why putting all reforms together would yield a combined liability change as shown in the web page: *the absolute values of the combined liability change are mostly expanding (expect year 2020 and 2021 where interception happens), and meanwhile the liability change shifts from being positive to being negative.*

Given this, I don't think there's anything wrong with our growth capabilities in TC, rather, it's just a nature of the reforms that we have implemented. 

cc @MattHJensen

**Comment by MattHJensen** [comment] 2016-08-25 12:08
@GoFroggyRun, great idea to split out the two reforms. I find this evidence compelling. Closing the issue after opening an issue to reactivate and rename the Growth section on TB: https://github.com/OpenSourcePolicyCenter/webapp-public/issues/314

**Closed by MattHJensen** 2016-08-25 12:08 UTC
