### ISSUE TITLE
User request: Child Tax Credit for units with negative AGI

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#1594] opened 2017-10-19 20:21 UTC
I received this email from @evtedeschi3 today:

>An additional question too: I’m trying to model a new fully refundable CTC that would be fully available to anyone below the phase-out AGI threshold — essentially no phase-in. It looks to me like the new CTC policy parameters will only affect tax units with positive AGI. Is that right? Is there a way I can work around that without getting into the Python code?

My understanding is he is correct that the child tax credit parameters only affect tax units with positive AGI, but it doesn't seem like it would be too difficult to add a parameter he could use (though I could be missing something).

Would anyone have time to work on this? I'm a little swamped right now with other projects and don't want to keep him waiting too long on this enhancement.

**Comment by martinholmer** [comment] 2017-10-19 21:43
@andersonfrailey said:
> I received this email from @evtedeschi3 today:
>> An additional question too: I’m trying to model a new fully refundable CTC that would be fully available to anyone below the phase-out AGI threshold — essentially no phase-in. It looks to me like the new CTC policy parameters will only affect tax units with positive AGI. Is that right? Is there a way I can work around that without getting into the Python code?

So, is he talking about using the **CTC_new** policy parameters to implement this reform?
There are seven of those policy parameters; search for "CTC_new" in [this documentation](http://open-source-economics.github.io/Tax-Calculator/) or view them on TaxBrain under the Refundable Credits section.

It looks to me as if turning off the current-law CTC and using the CTC_new parameters does allow the specification of a fully refundable child tax credit.  But maybe I'm missing something.

I don't understand what he means by "a new fully refundable CTC that would be fully available to anyone below the phase-out AGI threshold — essentially no phase-in".  I don't see what the phase-in rate has to do with the credit being fully refundable.   And what does "essentially no phase-in" mean?  No phase-in means setting the fully phased-in AGI at zero, right?

I think we need more information about what kind of reform he wants to simulate and then we'll be able to tell him if Tax-Calculator and TaxBrain can simulate his reform.

@MattHJensen

**Comment by martinholmer** [comment] 2017-10-19 21:51
@andersonfrailey said in issue #1594:
> My understanding is he is correct that the child tax credit parameters only affect tax units with positive AGI, but it doesn't seem like it would be too difficult to add a parameter he could use (though I could be missing something).

Yes, I see your/his point about the `CTC_new` function logic. 
Let me look into adding another parameter to allow a new CTC even for those with negative AGI.

@MattHJensen

**Comment by evtedeschi3** [comment] 2017-10-19 22:20
The issue is not full first-dollar refundability itself, which is easy to implement by setting the phase in rate very high. The issue is making it applicable to tax units with negative AGI, many of whom benefit from the current CTC/ACTC.

**Comment by martinholmer** [comment] 2017-10-19 22:45
@evtedeschi3 said:
> The issue is not full first-dollar refundability itself, which is easy to implement by setting the phase in rate very high. The issue is making it applicable to tax units with negative AGI, many of whom benefit from the current CTC/ACTC.

You are absolutely correct.  I was confused at first about the reform you wanted to simulate.

I've just about finished adding a policy parameter called `CTC_new_for_all` that by-passes the positive AGI phase-in logic.  When this parameter is set to true, everybody (even those with negative AGI) with eligible kids has a positive maximum new CTC amount, which can be phased-out at higher AGI values if desired.

It would be useful for me to test these enhancements on Friday.  Would you be willing to send me the values of the `CTC_new` parameters that you are interested in?  If so, I could simulate the reform(s) as a test of the logic enhancements.  If interested, you could send that info to me at martin dot holmer at gmail dot com.

Sorry for my earlier confusion.

@MattHJensen @andersonfrailey

**Comment by martinholmer** [comment] 2017-10-20 21:04
Issue #1594 has been resolved by pull request #1595, which is part of Tax-Calculator release 0.12.0.

**Closed by martinholmer** 2017-10-20 21:04 UTC
