### ISSUE TITLE
Calculator to Properly Read 08 puf Data

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#532] opened 2016-01-20 03:07 UTC
Currently a few other tax-related models are still using `08 puf`, thus it would be helpful for our calculator to produce sensible results using `08 puf` in order to interact with other models, and broaden our validation scope. 

Given that we were using `08 puf` as a primary input, most functions in the `functions.py` of current master should still work properly. There are, however, a few variables' names got changes. As an example, `p25380` in the `09 puf` was named `e25380` in the `08 puf`.

After #510 that has addressed concerns in #425, the calculator now will definitely be able to read `08 puf`, but cases as mentioned above might not be dealt with in an ideal way, in terms of making output sensible. Issues like this could be resolved within `records.py` when variables were recorded. 

cc @martinholmer @Amy-Xu @MattHJensen

**Comment by martinholmer** [comment] 2016-01-20 10:41
Sean said (with some clarifying edits):
> Currently a few other tax-related models are still using the 2008 IRS/SOI PUF for some reason, thus it would be helpful for our calculator to produce sensible results using the 2008 IRS/SOI PUF in order to interact with other models, and broaden our validation scope.
>
> Given that we were using the 2008 IRS/SOI PUF as part of our primary input, most functions in the functions.py of current master should still work properly. There are, however, a few variables whose name got changed by the IRS/SOI staff. As an example, p25380 in the 2009 IRS/SOI PUF was named e25380 in the 2008 IRS/SOI PUF.

Perhaps I'm misreading the PUF documentation prepared by the IRS/SOI staff, but it seems as if the 25380 change is not just a renaming of the same variable.  If you look at the [2009 PUF documentation](http://users.nber.org/~taxsim/gdb/gdb09.pdf), you see that the only 25380 variable is p25380, which is defined as ```Rent/Royalty Interest Expense```.  In the [2008 PUF documentation](http://users.nber.org/~taxsim/gdb/gdb08.pdf), you see that the only 25380 variable is e25380, which is defined as ```Rent/royalty expenses other interest, Schedule E , line 13```.  But notice that in 2008 there is also e25370, which is defined as ```Rent expenses mortgage interest, Schedule E, line 12```.  So, it would seem as if the 2009 p25380 is conceptually equal to the sum of 2008 e25380 and 2008 e25370.  I think that might be true because there is no 25370 variable in the 2009 IRS/SOI PUF.  Can others on the team clarify this situation?  Is my interpretation correct or incorrect?  If incorrect, what exactly is the relationship between the 2008 e25380 and the 2009 p25380 in the IRS/SOI PUF?

Sean continued to say:
> After #510 that has addressed concerns in #425, the calculator now will definitely be able to read 08 puf, but cases as mentioned above might not be dealt with in an ideal way, in terms of making output sensible. Issues like this could be resolved within records.py when variables were recorded.

There are a couple issues that need to be clarified.

(1) Trying to read into a Records object a csv file that contains all the variables in the 2008 IRS/SOI PUF file would fail.  The failure would be caused by the fact that some of the input file variable names are not in the Records.VALID_READ_VARS set.  This failure would occur even if all the E and P prefixes had been changed in the csv file to p and e prefixes.  Variable names not in the Records.VALID_READ_VARS set include, for example, e25370 and e25380 (as discussed above).  The Records.VALID_READ_VARS set contains the names of variables that the Tax-Calculator knows how to process.

(2) The suggestion ```Issues like this could be resolved within records.py when variables were recorded``` goes against the direction that Matt has laid out for the Tax-Calculator project as described in issue #436.  It seems likely that there will be considerable input data revisions that will need to be done for each model with which we cross-validate.  It is not a good idea to load all this cross-model-validation data-preparation code into the Records class.  We should have a separate directory and Python scripts to do this data-preparation work for each model against which we cross-validate.  Now the Tax-Calculator directory structure looks like this (in part):
```
    taxcalc
        tests
        validation
```
Right now the validation subdirectory contains only scripts used in the Internet-TAXSIM cross-validation.
Perhaps we should revise the directory structure to look like this:
```
    taxcalc
        tests
        validation
            Internet-TAXSIM
            Other-Model-A
            Other-Model-B
```
All the files currently in validation would be moved to validation/Internet-TAXSIM, and the other validation subdirectories would contain data-preparation scripts relevant to each additional model against which we cross-validate.  These subdirectories would also contain the scripts used to conduct the cross-validation and the results (just like the Internet-TAXSIM validation work).

This is just one idea.  Including these data-preparation scripts in the Tax-Calculator repository highlights the fact that the Tax-Calculator has been extensively validated against other models.  An alternative would be to put all these cross-validation data-preparation scripts in the taxdata repository.  That would be fine logically, but there would be less public awareness of the extensive validation work.  And we would still need validation subdirectories in the Tax-Calculator repository to hold scripts that conduct the cross-validation and show the results of that cross-validation.

Are there better approaches to organizing our work as we expand our cross-model-validation work?

cc @GoFroggyRun @MattHJensen @feenberg @Amy-Xu @talumbau

**Comment by GoFroggyRun** [comment] 2016-02-02 16:47
@martinholmer Thank you so much for your thoughtful comments. And sorry for the very late reply. 

So, for the moment, we decided to restrict the validation within the 22 input variables that the Internet Taxsim has. I would expect extracting the 22 variables from 08 puf to be relatively easier than reading all 08 puf data. This shall be a good way to expand the validation work. Also, most scripts in `SIMTAX` can be used with slight modifications. 

I'll open PR with initial `readme` file regarding validations using 08 puf very soon. As you suggested, I was thinking of modifying the directory like follow, despite that the scripts we used in two folders are somewhat similar:
```
    taxcalc
        tests
        validation
            Internet-TAXSIM
            08-PUF-Models
            Other-Model-B
```

Any comments, concerns or remarks would be appreciated.

**Comment by feenberg** [comment] 2016-02-02 18:20
OK, I am looking at line 47 of the 1040. In the pennies column I see "6 
.68". I don't know what the "6" is about, but presumably the ".68" is a 
tax rate. Line 47 is the sum of 44,45 and 46. That looks like .4+.28. So 
the surprise is that the AMT went up by more than the regular tax when you 
increased wages. So I look at Form 6251 and I am surprised to see line 34 
is zero with no change. That line is supposed to be line 44 from the 1040. 
I think that is the problem with the filled out forms, as if 197,763 is 
entered in line 34 of the 6251 it removes any AMT liability and leaves the 
MTR at .28. However, it doesn't resolve the question of the calculator. To 
examine that one would want to see a list of all the c-values before and 
after the penny change.

dan

**Comment by martinholmer** [comment] 2016-02-03 22:58
For those who were interested in issue #532, Calculator Should Be Able to Properly Read 2008 PUF Data, you might want to follow the conversation at issue #576, How to read raw IRS 2008 PUF variables into Tax-Calculator.

cc @MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment] 2016-02-19 20:15
Closing issue #532, *Calculator Should Be Able to Properly Read 2008 PUF Data*, because this discussion is continuing in issue #576, *How to read raw IRS 2008 PUF variables into Tax-Calculator*.

**Closed by martinholmer** 2016-02-19 20:15 UTC
