### ISSUE TITLE
Strange result from EITC reform

### ISSUE THREAD

**Issue by rickecon** [open-source-economics/Tax-Calculator#2017] opened 2018-06-08 22:14 UTC
@MattHJensen @hdoupe @martinholmer @jdebacker. I ran Tax-Calculator for a reform simulating an expanded EITC according to the Brown-Khanna GAIN Act. I used the [BrownKhanna.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/BrownKhanna.json) reform file from the reforms folder. If I turn off any behavioral responses, this policy should represent purely a tax cut for lots of individuals. My run of the microsimulation model shows 47,185,441.88 individuals claiming the expanded EITC after the reform. The histogram of those filers’ after tax income change is the following.

![ati_dif_2018_micro_pos](https://user-images.githubusercontent.com/4317690/41183206-0bc6482e-6b3f-11e8-9f9f-449b6830c975.png)

However, I am puzzled by the 13,128.45 individuals whose after tax income goes down. Their histogram is the following.

![ati_dif_2018_micro_neg](https://user-images.githubusercontent.com/4317690/41183220-21f7ec88-6b3f-11e8-82e3-a50b2666a537.png)

If behavioral response is turned off, there should not be anybody with a negative change in after-tax income.  Do any of you have any explanations for where these 13,128.5 individuals might be coming from?

**Comment by feenberg** [comment] 2018-06-09 14:19
On Fri, 8 Jun 2018, Richard Evans wrote:

> 
> @MattHJensen @hdoupe @martinholmer @jdebacker. I ran Tax-Calculator for a
> reform simulating an expanded EITC according to the Brown-Khanna GAIN Act. I
> used the BrownKhanna.json reform file from the reforms folder. If I turn off
> any behavioral responses, this policy should represent purely a tax cut for
> lots of individuals. My run of the microsimulation model shows 47,185,441.88
> individuals claiming the expanded EITC after the reform. The histogram of
> those filers’ after tax income change is the following.
> 
> ati_dif_2018_micro_pos
> 
> However, I am puzzled by the 13,128.45 individuals whose after tax income
> goes down. Their histogram is the following.
> 
> ati_dif_2018_micro_neg
> 
> If behavioral response is turned off, there should not be anybody with a
> negative change in after-tax income. Do any of you have any explanations for
> where these 13,128.5 individuals might be coming from?
>

The way to diagnose situations like this is not with data visualization, 
but by examining a single problematic record, possibly even filling out a 
1040 using the data supplied and the new rules. Comparing the hand 
calculation with the computer output (especially the intermediate values 
in the calculation) will quickly show the reason for the divergence in 
that record, and that will probably cover all the other cases as well.


Daniel Feenberg

**Comment by martinholmer** [comment] 2018-06-10 13:30
@rickecon said:
>  I ran Tax-Calculator for a reform simulating an expanded EITC according to the Brown-Khanna GAIN Act.
> I used the `BrownKhanna.json` reform file from the reforms folder and I turned off behavioral responses.

Thanks for your question, but it's difficult for others to help you find an answer because you've provided no information about how you generated the results you use to produce the graphs.  Anybody that might want to help would need to know the following:

1. Did you use the `tc` tool?  If so, what was the command you used?  What version of `tc` did you use?

2. Did you write a Python script?  If so, can you show us the script you wrote?

3. Did you generate the results that puzzle you some other way?  If so, can you explain?

There is a possibility that you have run across a bug in Tax-Calculator.  If so, we have no idea how to fix it because the lack of detail in issue #2017 makes it impossible to replicate your experience.

**Comment by MaxGhenis** [comment] 2018-06-11 22:22
@rickecon, you may find my #1938 relevant, where we're diagnosing a similar question regarding CTC reform. [This notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/ctc_2017_vs_repeal.ipynb) includes some commands to simplify specific records to get to a minimal reproducible example (though we're still working through it).

Did you use CPS or PUF data?

**Comment by martinholmer** [comment] 2018-08-06 14:09
@rickecon,  I hope your summer bootcamp went well.  In the coming weeks, I hope you have time to tell us more about what you did to get the puzzling EITC results you reported in Tax-Calculator issue #2017 on June 8.  In particular, to be able to help or fix a bug, we need answers to [these questions](https://github.com/open-source-economics/Tax-Calculator/issues/2017#issuecomment-396049273).

**Comment by MattHJensen** [comment] 2018-08-30 13:47
@rickecon, could you please answer [these questions](https://github.com/open-source-economics/Tax-Calculator/issues/2017#issuecomment-396049273) or close this issue?

**Comment by martinholmer** [comment] 2018-09-06 17:00
Closing Tax-Calculator issue #2017 because we were not able to replicate the strange EITC reform results.
If problems continue to occur, please report them in a new issue.

**Closed by martinholmer** 2018-09-06 17:00 UTC
Labels: question
